--create table AA_TABLE_ROWCOUNTS as
select 'ABSTRACT_TYPE' as TABLE_NAME, sysdate, count(*) as ROW_COUNT from ABSTRACT_TYPE union
select 'ACCOUNT_TYPE', sysdate, count(*) from ACCOUNT_TYPE union
select 'ACCT_DD_ATTR_DOC', sysdate, count(*) from ACCT_DD_ATTR_DOC union
select 'ACTIVITY_TYPE', sysdate, count(*) from ACTIVITY_TYPE union
select 'AFFILIATION_TYPE', sysdate, count(*) from AFFILIATION_TYPE union
select 'APPOINTMENT_TYPE', sysdate, count(*) from APPOINTMENT_TYPE union
select 'ARG_VALUE_LOOKUP', sysdate, count(*) from ARG_VALUE_LOOKUP union
select 'ATTACHMENT_FILE', sysdate, count(*) from ATTACHMENT_FILE union
select 'AWARD', sysdate, count(*) from AWARD union
select 'AWARD_AMOUNT_INFO', sysdate, count(*) from AWARD_AMOUNT_INFO union
select 'AWARD_AMOUNT_TRANSACTION', sysdate, count(*) from AWARD_AMOUNT_TRANSACTION union
select 'AWARD_AMT_FNA_DISTRIBUTION', sysdate, count(*) from AWARD_AMT_FNA_DISTRIBUTION union
select 'AWARD_APPROVED_EQUIPMENT', sysdate, count(*) from AWARD_APPROVED_EQUIPMENT union
select 'AWARD_APPROVED_FOREIGN_TRAVEL', sysdate, count(*) from AWARD_APPROVED_FOREIGN_TRAVEL union
select 'AWARD_APPROVED_SUBAWARDS', sysdate, count(*) from AWARD_APPROVED_SUBAWARDS union
select 'AWARD_ATTACHMENT', sysdate, count(*) from AWARD_ATTACHMENT union
select 'AWARD_ATTACHMENT_TYPE', sysdate, count(*) from AWARD_ATTACHMENT_TYPE union
select 'AWARD_BASIS_OF_PAYMENT', sysdate, count(*) from AWARD_BASIS_OF_PAYMENT union
select 'AWARD_BUDGET_DETAILS_EXT', sysdate, count(*) from AWARD_BUDGET_DETAILS_EXT union
select 'AWARD_BUDGET_EXT', sysdate, count(*) from AWARD_BUDGET_EXT union
select 'AWARD_BUDGET_LIMIT', sysdate, count(*) from AWARD_BUDGET_LIMIT union
select 'AWARD_BUDGET_PERIOD_EXT', sysdate, count(*) from AWARD_BUDGET_PERIOD_EXT union
select 'AWARD_BUDGET_STATUS', sysdate, count(*) from AWARD_BUDGET_STATUS union
select 'AWARD_BUDGET_TYPE', sysdate, count(*) from AWARD_BUDGET_TYPE union
select 'AWARD_CLOSEOUT', sysdate, count(*) from AWARD_CLOSEOUT union
select 'AWARD_COMMENT', sysdate, count(*) from AWARD_COMMENT union
select 'AWARD_COST_SHARE', sysdate, count(*) from AWARD_COST_SHARE union
select 'AWARD_CUSTOM_DATA', sysdate, count(*) from AWARD_CUSTOM_DATA union
select 'AWARD_DOCUMENT', sysdate, count(*) from AWARD_DOCUMENT union
select 'AWARD_EXEMPT_NUMBER', sysdate, count(*) from AWARD_EXEMPT_NUMBER union
select 'AWARD_FUNDING_PROPOALS_BACKUP', sysdate, count(*) from AWARD_FUNDING_PROPOALS_BACKUP union
select 'AWARD_FUNDING_PROPOSALS', sysdate, count(*) from AWARD_FUNDING_PROPOSALS union
select 'AWARD_HIERARCHY', sysdate, count(*) from AWARD_HIERARCHY union
select 'AWARD_IDC_RATE', sysdate, count(*) from AWARD_IDC_RATE union
select 'AWARD_METHOD_OF_PAYMENT', sysdate, count(*) from AWARD_METHOD_OF_PAYMENT union
select 'AWARD_NOTEPAD', sysdate, count(*) from AWARD_NOTEPAD union
select 'AWARD_PAYMENT_SCHEDULE', sysdate, count(*) from AWARD_PAYMENT_SCHEDULE union
select 'AWARD_PERSONS', sysdate, count(*) from AWARD_PERSONS union
select 'AWARD_PERSON_CREDIT_SPLITS', sysdate, count(*) from AWARD_PERSON_CREDIT_SPLITS union
select 'AWARD_PERSON_UNITS', sysdate, count(*) from AWARD_PERSON_UNITS union
select 'AWARD_PERS_UNIT_CRED_SPLITS', sysdate, count(*) from AWARD_PERS_UNIT_CRED_SPLITS union
select 'AWARD_REPORT_TERMS', sysdate, count(*) from AWARD_REPORT_TERMS union
select 'AWARD_REP_TERMS_RECNT', sysdate, count(*) from AWARD_REP_TERMS_RECNT union
select 'AWARD_SCIENCE_KEYWORD', sysdate, count(*) from AWARD_SCIENCE_KEYWORD union
select 'AWARD_SPECIAL_REVIEW', sysdate, count(*) from AWARD_SPECIAL_REVIEW union
select 'AWARD_SPONSOR_CONTACTS', sysdate, count(*) from AWARD_SPONSOR_CONTACTS union
select 'AWARD_SPONSOR_TERM', sysdate, count(*) from AWARD_SPONSOR_TERM union
select 'AWARD_STATUS', sysdate, count(*) from AWARD_STATUS union
select 'AWARD_SYNC_CHANGE', sysdate, count(*) from AWARD_SYNC_CHANGE union
select 'AWARD_SYNC_LOG', sysdate, count(*) from AWARD_SYNC_LOG union
select 'AWARD_SYNC_STATUS', sysdate, count(*) from AWARD_SYNC_STATUS union
select 'AWARD_TEMPLATE', sysdate, count(*) from AWARD_TEMPLATE union
select 'AWARD_TEMPLATE_COMMENTS', sysdate, count(*) from AWARD_TEMPLATE_COMMENTS union
select 'AWARD_TEMPLATE_CONTACT', sysdate, count(*) from AWARD_TEMPLATE_CONTACT union
select 'AWARD_TEMPLATE_REPORT_TERMS', sysdate, count(*) from AWARD_TEMPLATE_REPORT_TERMS union
select 'AWARD_TEMPLATE_TERMS', sysdate, count(*) from AWARD_TEMPLATE_TERMS union
select 'AWARD_TEMPL_REP_TERMS_RECNT', sysdate, count(*) from AWARD_TEMPL_REP_TERMS_RECNT union
select 'AWARD_TRANSACTION_TYPE', sysdate, count(*) from AWARD_TRANSACTION_TYPE union
select 'AWARD_TRANSFERRING_SPONSOR', sysdate, count(*) from AWARD_TRANSFERRING_SPONSOR union
select 'AWARD_TYPE', sysdate, count(*) from AWARD_TYPE union
select 'AWARD_UNIT_CONTACTS', sysdate, count(*) from AWARD_UNIT_CONTACTS union
select 'AWD_BGT_DET_CAL_AMTS_EXT', sysdate, count(*) from AWD_BGT_DET_CAL_AMTS_EXT union
select 'AWD_BGT_PER_SUM_CALC_AMT', sysdate, count(*) from AWD_BGT_PER_SUM_CALC_AMT union
select 'AWD_BUDGET_PER_CAL_AMTS_EXT', sysdate, count(*) from AWD_BUDGET_PER_CAL_AMTS_EXT union
select 'AWD_BUDGET_PER_DET_EXT', sysdate, count(*) from AWD_BUDGET_PER_DET_EXT union
select 'BATCH_CORRESPONDENCE', sysdate, count(*) from BATCH_CORRESPONDENCE union
select 'BATCH_CORRESPONDENCE_DETAIL', sysdate, count(*) from BATCH_CORRESPONDENCE_DETAIL union
select 'BUDGET', sysdate, count(*) from BUDGET union
select 'BUDGET_CATEGORY', sysdate, count(*) from BUDGET_CATEGORY union
select 'BUDGET_CATEGORY_MAPPING', sysdate, count(*) from BUDGET_CATEGORY_MAPPING union
select 'BUDGET_CATEGORY_MAPS', sysdate, count(*) from BUDGET_CATEGORY_MAPS union
select 'BUDGET_CATEGORY_TYPE', sysdate, count(*) from BUDGET_CATEGORY_TYPE union
select 'BUDGET_DETAILS', sysdate, count(*) from BUDGET_DETAILS union
select 'BUDGET_DETAILS_CAL_AMTS', sysdate, count(*) from BUDGET_DETAILS_CAL_AMTS union
select 'BUDGET_DOCUMENT', sysdate, count(*) from BUDGET_DOCUMENT union
select 'BUDGET_MODULAR', sysdate, count(*) from BUDGET_MODULAR union
select 'BUDGET_MODULAR_IDC', sysdate, count(*) from BUDGET_MODULAR_IDC union
select 'BUDGET_PERIODS', sysdate, count(*) from BUDGET_PERIODS union
select 'BUDGET_PERIOD_TYPE', sysdate, count(*) from BUDGET_PERIOD_TYPE union
select 'BUDGET_PERSONNEL_CAL_AMTS', sysdate, count(*) from BUDGET_PERSONNEL_CAL_AMTS union
select 'BUDGET_PERSONNEL_DETAILS', sysdate, count(*) from BUDGET_PERSONNEL_DETAILS union
select 'BUDGET_PERSONS', sysdate, count(*) from BUDGET_PERSONS union
select 'BUDGET_PER_DET_RATE_AND_BASE', sysdate, count(*) from BUDGET_PER_DET_RATE_AND_BASE union
select 'BUDGET_PROJECT_INCOME', sysdate, count(*) from BUDGET_PROJECT_INCOME union
select 'BUDGET_RATE_AND_BASE', sysdate, count(*) from BUDGET_RATE_AND_BASE union
select 'BUDGET_STATUS', sysdate, count(*) from BUDGET_STATUS union
select 'BUDGET_SUB_AWARDS', sysdate, count(*) from BUDGET_SUB_AWARDS union
select 'BUDGET_SUB_AWARD_ATT', sysdate, count(*) from BUDGET_SUB_AWARD_ATT union
select 'BUDGET_SUB_AWARD_FILES', sysdate, count(*) from BUDGET_SUB_AWARD_FILES union
select 'CARRIER_TYPE', sysdate, count(*) from CARRIER_TYPE union
select 'CFDA', sysdate, count(*) from CFDA union
select 'CITIZENSHIP_TYPE_T', sysdate, count(*) from CITIZENSHIP_TYPE_T union
select 'CLOSEOUT_REPORT_TYPE', sysdate, count(*) from CLOSEOUT_REPORT_TYPE union
select 'COEUS_MODULE', sysdate, count(*) from COEUS_MODULE union
select 'COEUS_SUB_MODULE', sysdate, count(*) from COEUS_SUB_MODULE union
select 'COMMENT_TYPE', sysdate, count(*) from COMMENT_TYPE union
select 'COMMITTEE', sysdate, count(*) from COMMITTEE union
select 'COMMITTEE_DOCUMENT', sysdate, count(*) from COMMITTEE_DOCUMENT union
select 'COMMITTEE_TYPE', sysdate, count(*) from COMMITTEE_TYPE union
select 'COMM_BATCH_CORRESP', sysdate, count(*) from COMM_BATCH_CORRESP union
select 'COMM_BATCH_CORRESP_DETAIL', sysdate, count(*) from COMM_BATCH_CORRESP_DETAIL union
select 'COMM_DECISION_MOTION_TYPE', sysdate, count(*) from COMM_DECISION_MOTION_TYPE union
select 'COMM_MEMBERSHIPS', sysdate, count(*) from COMM_MEMBERSHIPS union
select 'COMM_MEMBERSHIP_TYPE', sysdate, count(*) from COMM_MEMBERSHIP_TYPE union
select 'COMM_MEMBER_EXPERTISE', sysdate, count(*) from COMM_MEMBER_EXPERTISE union
select 'COMM_MEMBER_ROLES', sysdate, count(*) from COMM_MEMBER_ROLES union
select 'COMM_RESEARCH_AREAS', sysdate, count(*) from COMM_RESEARCH_AREAS union
select 'COMM_SCHEDULE', sysdate, count(*) from COMM_SCHEDULE union
select 'COMM_SCHEDULE_ACT_ITEMS', sysdate, count(*) from COMM_SCHEDULE_ACT_ITEMS union
select 'COMM_SCHEDULE_ATTENDANCE', sysdate, count(*) from COMM_SCHEDULE_ATTENDANCE union
select 'COMM_SCHEDULE_FREQUENCY', sysdate, count(*) from COMM_SCHEDULE_FREQUENCY union
select 'COMM_SCHEDULE_MINUTES', sysdate, count(*) from COMM_SCHEDULE_MINUTES union
select 'COMM_SCHEDULE_MINUTE_DOC', sysdate, count(*) from COMM_SCHEDULE_MINUTE_DOC union
select 'CONTACT_TYPE', sysdate, count(*) from CONTACT_TYPE union
select 'CORRESPONDENT_TYPE', sysdate, count(*) from CORRESPONDENT_TYPE union
select 'COST_ELEMENT', sysdate, count(*) from COST_ELEMENT union
select 'COST_SHARE_TYPE', sysdate, count(*) from COST_SHARE_TYPE union
select 'CUSTOM_ATTRIBUTE', sysdate, count(*) from CUSTOM_ATTRIBUTE union
select 'CUSTOM_ATTRIBUTE_DATA_TYPE', sysdate, count(*) from CUSTOM_ATTRIBUTE_DATA_TYPE union
select 'CUSTOM_ATTRIBUTE_DOCUMENT', sysdate, count(*) from CUSTOM_ATTRIBUTE_DOCUMENT union
select 'CUSTOM_ATTRIBUTE_DOC_VALUE', sysdate, count(*) from CUSTOM_ATTRIBUTE_DOC_VALUE union
select 'DEADLINE_TYPE', sysdate, count(*) from DEADLINE_TYPE union
select 'DEGREE_TYPE', sysdate, count(*) from DEGREE_TYPE union
select 'DISTRIBUTION', sysdate, count(*) from DISTRIBUTION union
select 'DOCUMENT_NEXTVALUE', sysdate, count(*) from DOCUMENT_NEXTVALUE union
select 'EPS_PROPOSAL', sysdate, count(*) from EPS_PROPOSAL union
select 'EPS_PROPOSAL_BUDGET_EXT', sysdate, count(*) from EPS_PROPOSAL_BUDGET_EXT union
select 'EPS_PROPOSAL_BUDGET_STATUS', sysdate, count(*) from EPS_PROPOSAL_BUDGET_STATUS union
select 'EPS_PROPOSAL_DOCUMENT', sysdate, count(*) from EPS_PROPOSAL_DOCUMENT union
select 'EPS_PROPOSAL_STATUS', sysdate, count(*) from EPS_PROPOSAL_STATUS union
select 'EPS_PROP_ABSTRACT', sysdate, count(*) from EPS_PROP_ABSTRACT union
select 'EPS_PROP_CHANGED_DATA', sysdate, count(*) from EPS_PROP_CHANGED_DATA union
select 'EPS_PROP_COLUMNS_TO_ALTER', sysdate, count(*) from EPS_PROP_COLUMNS_TO_ALTER union
select 'EPS_PROP_CONG_DISTRICT', sysdate, count(*) from EPS_PROP_CONG_DISTRICT union
select 'EPS_PROP_COST_SHARING', sysdate, count(*) from EPS_PROP_COST_SHARING union
select 'EPS_PROP_EXEMPT_NUMBER', sysdate, count(*) from EPS_PROP_EXEMPT_NUMBER union
select 'EPS_PROP_IDC_RATE', sysdate, count(*) from EPS_PROP_IDC_RATE union
select 'EPS_PROP_LA_RATES', sysdate, count(*) from EPS_PROP_LA_RATES union
select 'EPS_PROP_LOCATION', sysdate, count(*) from EPS_PROP_LOCATION union
select 'EPS_PROP_PERSON', sysdate, count(*) from EPS_PROP_PERSON union
select 'EPS_PROP_PERSON_BIO', sysdate, count(*) from EPS_PROP_PERSON_BIO union
select 'EPS_PROP_PERSON_BIO_ATTACHMENT', sysdate, count(*) from EPS_PROP_PERSON_BIO_ATTACHMENT union
select 'EPS_PROP_PERSON_DEGREE', sysdate, count(*) from EPS_PROP_PERSON_DEGREE union
select 'EPS_PROP_PERSON_EXT', sysdate, count(*) from EPS_PROP_PERSON_EXT union
select 'EPS_PROP_PERSON_ROLE', sysdate, count(*) from EPS_PROP_PERSON_ROLE union
select 'EPS_PROP_PERSON_UNITS', sysdate, count(*) from EPS_PROP_PERSON_UNITS union
select 'EPS_PROP_PERS_YNQ', sysdate, count(*) from EPS_PROP_PERS_YNQ union
select 'EPS_PROP_PER_CREDIT_SPLIT', sysdate, count(*) from EPS_PROP_PER_CREDIT_SPLIT union
select 'EPS_PROP_PER_DOC_TYPE', sysdate, count(*) from EPS_PROP_PER_DOC_TYPE union
select 'EPS_PROP_RATES', sysdate, count(*) from EPS_PROP_RATES union
select 'EPS_PROP_SCIENCE_KEYWORD', sysdate, count(*) from EPS_PROP_SCIENCE_KEYWORD union
select 'EPS_PROP_SITES', sysdate, count(*) from EPS_PROP_SITES union
select 'EPS_PROP_SPECIAL_REVIEW', sysdate, count(*) from EPS_PROP_SPECIAL_REVIEW union
select 'EPS_PROP_UNIT_CREDIT_SPLIT', sysdate, count(*) from EPS_PROP_UNIT_CREDIT_SPLIT union
select 'EPS_PROP_USER_ROLES', sysdate, count(*) from EPS_PROP_USER_ROLES union
select 'EPS_PROP_YNQ', sysdate, count(*) from EPS_PROP_YNQ union
select 'EXEMPTION_TYPE', sysdate, count(*) from EXEMPTION_TYPE union
select 'EXEMPT_STUDIES_CHECKLIST', sysdate, count(*) from EXEMPT_STUDIES_CHECKLIST union
select 'EXPEDITED_REVIEW_CHECKLIST', sysdate, count(*) from EXPEDITED_REVIEW_CHECKLIST union
select 'FP_DOC_TYPE_T', sysdate, count(*) from FP_DOC_TYPE_T union
select 'FREQUENCY', sysdate, count(*) from FREQUENCY union
select 'FREQUENCY_BASE', sysdate, count(*) from FREQUENCY_BASE union
select 'FUNDING_SOURCE_TYPE', sysdate, count(*) from FUNDING_SOURCE_TYPE union
select 'GROUP_TYPES', sysdate, count(*) from GROUP_TYPES union
select 'IDC_RATE_TYPE', sysdate, count(*) from IDC_RATE_TYPE union
select 'INSTITUTE_LA_RATES', sysdate, count(*) from INSTITUTE_LA_RATES union
select 'INSTITUTE_PROPOSAL_DOCUMENT', sysdate, count(*) from INSTITUTE_PROPOSAL_DOCUMENT union
select 'INSTITUTE_RATES', sysdate, count(*) from INSTITUTE_RATES union
select 'INV_CREDIT_TYPE', sysdate, count(*) from INV_CREDIT_TYPE union
select 'IP_REVIEW', sysdate, count(*) from IP_REVIEW union
select 'IP_REVIEW_ACTIVITY_TYPE', sysdate, count(*) from IP_REVIEW_ACTIVITY_TYPE union
select 'IP_REVIEW_REQ_TYPE', sysdate, count(*) from IP_REVIEW_REQ_TYPE union
select 'IP_REVIEW_RESULT_TYPE', sysdate, count(*) from IP_REVIEW_RESULT_TYPE union
select 'JOB_CODE', sysdate, count(*) from JOB_CODE union
select 'KC_QRTZ_BLOB_TRIGGERS', sysdate, count(*) from KC_QRTZ_BLOB_TRIGGERS union
select 'KC_QRTZ_CALENDARS', sysdate, count(*) from KC_QRTZ_CALENDARS union
select 'KC_QRTZ_CRON_TRIGGERS', sysdate, count(*) from KC_QRTZ_CRON_TRIGGERS union
select 'KC_QRTZ_FIRED_TRIGGERS', sysdate, count(*) from KC_QRTZ_FIRED_TRIGGERS union
select 'KC_QRTZ_JOB_DETAILS', sysdate, count(*) from KC_QRTZ_JOB_DETAILS union
select 'KC_QRTZ_JOB_LISTENERS', sysdate, count(*) from KC_QRTZ_JOB_LISTENERS union
select 'KC_QRTZ_LOCKS', sysdate, count(*) from KC_QRTZ_LOCKS union
select 'KC_QRTZ_PAUSED_TRIGGER_GRPS', sysdate, count(*) from KC_QRTZ_PAUSED_TRIGGER_GRPS union
select 'KC_QRTZ_SCHEDULER_STATE', sysdate, count(*) from KC_QRTZ_SCHEDULER_STATE union
select 'KC_QRTZ_SIMPLE_TRIGGERS', sysdate, count(*) from KC_QRTZ_SIMPLE_TRIGGERS union
select 'KC_QRTZ_TRIGGERS', sysdate, count(*) from KC_QRTZ_TRIGGERS union
select 'KC_QRTZ_TRIGGER_LISTENERS', sysdate, count(*) from KC_QRTZ_TRIGGER_LISTENERS union
select 'KRA_USER', sysdate, count(*) from KRA_USER union
select 'KREN_CHNL_PRODCR_T', sysdate, count(*) from KREN_CHNL_PRODCR_T union
select 'KREN_CHNL_SUBSCRP_T', sysdate, count(*) from KREN_CHNL_SUBSCRP_T union
select 'KREN_CHNL_T', sysdate, count(*) from KREN_CHNL_T union
select 'KREN_CNTNT_TYP_T', sysdate, count(*) from KREN_CNTNT_TYP_T union
select 'KREN_MSG_DELIV_T', sysdate, count(*) from KREN_MSG_DELIV_T union
select 'KREN_MSG_T', sysdate, count(*) from KREN_MSG_T union
select 'KREN_NTFCTN_MSG_DELIV_T', sysdate, count(*) from KREN_NTFCTN_MSG_DELIV_T union
select 'KREN_NTFCTN_T', sysdate, count(*) from KREN_NTFCTN_T union
select 'KREN_PRIO_T', sysdate, count(*) from KREN_PRIO_T union
select 'KREN_PRODCR_T', sysdate, count(*) from KREN_PRODCR_T union
select 'KREN_RECIP_DELIV_T', sysdate, count(*) from KREN_RECIP_DELIV_T union
select 'KREN_RECIP_LIST_T', sysdate, count(*) from KREN_RECIP_LIST_T union
select 'KREN_RECIP_PREFS_T', sysdate, count(*) from KREN_RECIP_PREFS_T union
select 'KREN_RECIP_T', sysdate, count(*) from KREN_RECIP_T union
select 'KREN_RVWER_T', sysdate, count(*) from KREN_RVWER_T union
select 'KREN_SNDR_T', sysdate, count(*) from KREN_SNDR_T union
select 'KREW_ACTN_ITM_T', sysdate, count(*) from KREW_ACTN_ITM_T union
select 'KREW_ACTN_RQST_T', sysdate, count(*) from KREW_ACTN_RQST_T union
select 'KREW_ACTN_TKN_T', sysdate, count(*) from KREW_ACTN_TKN_T union
select 'KREW_APP_DOC_STAT_TRAN_T', sysdate, count(*) from KREW_APP_DOC_STAT_TRAN_T union
select 'KREW_ATT_T', sysdate, count(*) from KREW_ATT_T union
select 'KREW_DLGN_RSP_T', sysdate, count(*) from KREW_DLGN_RSP_T union
select 'KREW_DOC_HDR_CNTNT_T', sysdate, count(*) from KREW_DOC_HDR_CNTNT_T union
select 'KREW_DOC_HDR_EXT_DT_T', sysdate, count(*) from KREW_DOC_HDR_EXT_DT_T union
select 'KREW_DOC_HDR_EXT_FLT_T', sysdate, count(*) from KREW_DOC_HDR_EXT_FLT_T union
select 'KREW_DOC_HDR_EXT_LONG_T', sysdate, count(*) from KREW_DOC_HDR_EXT_LONG_T union
select 'KREW_DOC_HDR_EXT_T', sysdate, count(*) from KREW_DOC_HDR_EXT_T union
select 'KREW_DOC_HDR_T', sysdate, count(*) from KREW_DOC_HDR_T union
select 'KREW_DOC_LNK_T', sysdate, count(*) from KREW_DOC_LNK_T union
select 'KREW_DOC_NTE_T', sysdate, count(*) from KREW_DOC_NTE_T union
select 'KREW_DOC_TYP_APP_DOC_STAT_T', sysdate, count(*) from KREW_DOC_TYP_APP_DOC_STAT_T union
select 'KREW_DOC_TYP_ATTR_T', sysdate, count(*) from KREW_DOC_TYP_ATTR_T union
select 'KREW_DOC_TYP_PLCY_RELN_T', sysdate, count(*) from KREW_DOC_TYP_PLCY_RELN_T union
select 'KREW_DOC_TYP_PROC_T', sysdate, count(*) from KREW_DOC_TYP_PROC_T union
select 'KREW_DOC_TYP_T', sysdate, count(*) from KREW_DOC_TYP_T union
select 'KREW_EDL_ASSCTN_T', sysdate, count(*) from KREW_EDL_ASSCTN_T union
select 'KREW_EDL_DEF_T', sysdate, count(*) from KREW_EDL_DEF_T union
select 'KREW_EDL_DMP_T', sysdate, count(*) from KREW_EDL_DMP_T union
select 'KREW_EDL_FLD_DMP_T', sysdate, count(*) from KREW_EDL_FLD_DMP_T union
select 'KREW_HLP_T', sysdate, count(*) from KREW_HLP_T union
select 'KREW_INIT_RTE_NODE_INSTN_T', sysdate, count(*) from KREW_INIT_RTE_NODE_INSTN_T union
select 'KREW_OUT_BOX_ITM_T', sysdate, count(*) from KREW_OUT_BOX_ITM_T union
select 'KREW_RIA_DOCTYPE_MAP_T', sysdate, count(*) from KREW_RIA_DOCTYPE_MAP_T union
select 'KREW_RIA_DOC_T', sysdate, count(*) from KREW_RIA_DOC_T union
select 'KREW_RMV_RPLC_DOC_T', sysdate, count(*) from KREW_RMV_RPLC_DOC_T union
select 'KREW_RMV_RPLC_GRP_T', sysdate, count(*) from KREW_RMV_RPLC_GRP_T union
select 'KREW_RMV_RPLC_RULE_T', sysdate, count(*) from KREW_RMV_RPLC_RULE_T union
select 'KREW_RTE_BRCH_PROTO_T', sysdate, count(*) from KREW_RTE_BRCH_PROTO_T union
select 'KREW_RTE_BRCH_ST_T', sysdate, count(*) from KREW_RTE_BRCH_ST_T union
select 'KREW_RTE_BRCH_T', sysdate, count(*) from KREW_RTE_BRCH_T union
select 'KREW_RTE_NODE_CFG_PARM_T', sysdate, count(*) from KREW_RTE_NODE_CFG_PARM_T union
select 'KREW_RTE_NODE_INSTN_LNK_T', sysdate, count(*) from KREW_RTE_NODE_INSTN_LNK_T union
select 'KREW_RTE_NODE_INSTN_ST_T', sysdate, count(*) from KREW_RTE_NODE_INSTN_ST_T union
select 'KREW_RTE_NODE_INSTN_T', sysdate, count(*) from KREW_RTE_NODE_INSTN_T union
select 'KREW_RTE_NODE_LNK_T', sysdate, count(*) from KREW_RTE_NODE_LNK_T union
select 'KREW_RTE_NODE_T', sysdate, count(*) from KREW_RTE_NODE_T union
select 'KREW_RULE_ATTR_T', sysdate, count(*) from KREW_RULE_ATTR_T union
select 'KREW_RULE_EXPR_T', sysdate, count(*) from KREW_RULE_EXPR_T union
select 'KREW_RULE_EXT_T', sysdate, count(*) from KREW_RULE_EXT_T union
select 'KREW_RULE_EXT_VAL_T', sysdate, count(*) from KREW_RULE_EXT_VAL_T union
select 'KREW_RULE_RSP_T', sysdate, count(*) from KREW_RULE_RSP_T union
select 'KREW_RULE_T', sysdate, count(*) from KREW_RULE_T union
select 'KREW_RULE_TMPL_ATTR_T', sysdate, count(*) from KREW_RULE_TMPL_ATTR_T union
select 'KREW_RULE_TMPL_OPTN_T', sysdate, count(*) from KREW_RULE_TMPL_OPTN_T union
select 'KREW_RULE_TMPL_T', sysdate, count(*) from KREW_RULE_TMPL_T union
select 'KREW_STYLE_T', sysdate, count(*) from KREW_STYLE_T union
select 'KREW_USR_OPTN_T', sysdate, count(*) from KREW_USR_OPTN_T union
select 'KRIM_ADDR_TYP_T', sysdate, count(*) from KRIM_ADDR_TYP_T union
select 'KRIM_AFLTN_TYP_T', sysdate, count(*) from KRIM_AFLTN_TYP_T union
select 'KRIM_ATTR_DEFN_T', sysdate, count(*) from KRIM_ATTR_DEFN_T union
select 'KRIM_CTZNSHP_STAT_T', sysdate, count(*) from KRIM_CTZNSHP_STAT_T union
select 'KRIM_DLGN_MBR_ATTR_DATA_T', sysdate, count(*) from KRIM_DLGN_MBR_ATTR_DATA_T union
select 'KRIM_DLGN_MBR_T', sysdate, count(*) from KRIM_DLGN_MBR_T union
select 'KRIM_DLGN_T', sysdate, count(*) from KRIM_DLGN_T union
select 'KRIM_EMAIL_TYP_T', sysdate, count(*) from KRIM_EMAIL_TYP_T union
select 'KRIM_EMP_STAT_T', sysdate, count(*) from KRIM_EMP_STAT_T union
select 'KRIM_EMP_TYP_T', sysdate, count(*) from KRIM_EMP_TYP_T union
select 'KRIM_ENTITY_ADDR_T', sysdate, count(*) from KRIM_ENTITY_ADDR_T union
select 'KRIM_ENTITY_AFLTN_T', sysdate, count(*) from KRIM_ENTITY_AFLTN_T union
select 'KRIM_ENTITY_BIO_T', sysdate, count(*) from KRIM_ENTITY_BIO_T union
select 'KRIM_ENTITY_CACHE_T', sysdate, count(*) from KRIM_ENTITY_CACHE_T union
select 'KRIM_ENTITY_CTZNSHP_T', sysdate, count(*) from KRIM_ENTITY_CTZNSHP_T union
select 'KRIM_ENTITY_EMAIL_T', sysdate, count(*) from KRIM_ENTITY_EMAIL_T union
select 'KRIM_ENTITY_EMP_INFO_T', sysdate, count(*) from KRIM_ENTITY_EMP_INFO_T union
select 'KRIM_ENTITY_ENT_TYP_T', sysdate, count(*) from KRIM_ENTITY_ENT_TYP_T union
select 'KRIM_ENTITY_ETHNIC_T', sysdate, count(*) from KRIM_ENTITY_ETHNIC_T union
select 'KRIM_ENTITY_EXT_ID_T', sysdate, count(*) from KRIM_ENTITY_EXT_ID_T union
select 'KRIM_ENTITY_NM_T', sysdate, count(*) from KRIM_ENTITY_NM_T union
select 'KRIM_ENTITY_PHONE_T', sysdate, count(*) from KRIM_ENTITY_PHONE_T union
select 'KRIM_ENTITY_PRIV_PREF_T', sysdate, count(*) from KRIM_ENTITY_PRIV_PREF_T union
select 'KRIM_ENTITY_RESIDENCY_T', sysdate, count(*) from KRIM_ENTITY_RESIDENCY_T union
select 'KRIM_ENTITY_T', sysdate, count(*) from KRIM_ENTITY_T union
select 'KRIM_ENTITY_VISA_T', sysdate, count(*) from KRIM_ENTITY_VISA_T union
select 'KRIM_ENT_NM_TYP_T', sysdate, count(*) from KRIM_ENT_NM_TYP_T union
select 'KRIM_ENT_TYP_T', sysdate, count(*) from KRIM_ENT_TYP_T union
select 'KRIM_EXT_ID_TYP_T', sysdate, count(*) from KRIM_EXT_ID_TYP_T union
select 'KRIM_GRP_ATTR_DATA_T', sysdate, count(*) from KRIM_GRP_ATTR_DATA_T union
select 'KRIM_GRP_DOCUMENT_T', sysdate, count(*) from KRIM_GRP_DOCUMENT_T union
select 'KRIM_GRP_MBR_T', sysdate, count(*) from KRIM_GRP_MBR_T union
select 'KRIM_GRP_T', sysdate, count(*) from KRIM_GRP_T union
select 'KRIM_PERM_ATTR_DATA_T', sysdate, count(*) from KRIM_PERM_ATTR_DATA_T union
select 'KRIM_PERM_T', sysdate, count(*) from KRIM_PERM_T union
select 'KRIM_PERM_TMPL_T', sysdate, count(*) from KRIM_PERM_TMPL_T union
select 'KRIM_PERSON_DOCUMENT_T', sysdate, count(*) from KRIM_PERSON_DOCUMENT_T union
select 'KRIM_PHONE_TYP_T', sysdate, count(*) from KRIM_PHONE_TYP_T union
select 'KRIM_PND_ADDR_MT', sysdate, count(*) from KRIM_PND_ADDR_MT union
select 'KRIM_PND_AFLTN_MT', sysdate, count(*) from KRIM_PND_AFLTN_MT union
select 'KRIM_PND_CTZNSHP_MT', sysdate, count(*) from KRIM_PND_CTZNSHP_MT union
select 'KRIM_PND_DLGN_MBR_ATTR_DATA_T', sysdate, count(*) from KRIM_PND_DLGN_MBR_ATTR_DATA_T union
select 'KRIM_PND_DLGN_MBR_T', sysdate, count(*) from KRIM_PND_DLGN_MBR_T union
select 'KRIM_PND_DLGN_T', sysdate, count(*) from KRIM_PND_DLGN_T union
select 'KRIM_PND_EMAIL_MT', sysdate, count(*) from KRIM_PND_EMAIL_MT union
select 'KRIM_PND_EMP_INFO_MT', sysdate, count(*) from KRIM_PND_EMP_INFO_MT union
select 'KRIM_PND_GRP_ATTR_DATA_T', sysdate, count(*) from KRIM_PND_GRP_ATTR_DATA_T union
select 'KRIM_PND_GRP_MBR_T', sysdate, count(*) from KRIM_PND_GRP_MBR_T union
select 'KRIM_PND_GRP_PRNCPL_MT', sysdate, count(*) from KRIM_PND_GRP_PRNCPL_MT union
select 'KRIM_PND_NM_MT', sysdate, count(*) from KRIM_PND_NM_MT union
select 'KRIM_PND_PHONE_MT', sysdate, count(*) from KRIM_PND_PHONE_MT union
select 'KRIM_PND_PRIV_PREF_MT', sysdate, count(*) from KRIM_PND_PRIV_PREF_MT union
select 'KRIM_PND_ROLE_MBR_ATTR_DATA_MT', sysdate, count(*) from KRIM_PND_ROLE_MBR_ATTR_DATA_MT union
select 'KRIM_PND_ROLE_MBR_MT', sysdate, count(*) from KRIM_PND_ROLE_MBR_MT union
select 'KRIM_PND_ROLE_MT', sysdate, count(*) from KRIM_PND_ROLE_MT union
select 'KRIM_PND_ROLE_PERM_T', sysdate, count(*) from KRIM_PND_ROLE_PERM_T union
select 'KRIM_PND_ROLE_RSP_ACTN_MT', sysdate, count(*) from KRIM_PND_ROLE_RSP_ACTN_MT union
select 'KRIM_PND_ROLE_RSP_T', sysdate, count(*) from KRIM_PND_ROLE_RSP_T union
select 'KRIM_PRNCPL_T', sysdate, count(*) from KRIM_PRNCPL_T union
select 'KRIM_ROLE_DOCUMENT_T', sysdate, count(*) from KRIM_ROLE_DOCUMENT_T union
select 'KRIM_ROLE_MBR_ATTR_DATA_T', sysdate, count(*) from KRIM_ROLE_MBR_ATTR_DATA_T union
select 'KRIM_ROLE_MBR_T', sysdate, count(*) from KRIM_ROLE_MBR_T union
select 'KRIM_ROLE_PERM_T', sysdate, count(*) from KRIM_ROLE_PERM_T union
select 'KRIM_ROLE_RSP_ACTN_T', sysdate, count(*) from KRIM_ROLE_RSP_ACTN_T union
select 'KRIM_ROLE_RSP_T', sysdate, count(*) from KRIM_ROLE_RSP_T union
select 'KRIM_ROLE_T', sysdate, count(*) from KRIM_ROLE_T union
select 'KRIM_RSP_ATTR_DATA_T', sysdate, count(*) from KRIM_RSP_ATTR_DATA_T union
select 'KRIM_RSP_T', sysdate, count(*) from KRIM_RSP_T union
select 'KRIM_RSP_TMPL_T', sysdate, count(*) from KRIM_RSP_TMPL_T union
select 'KRIM_TYP_ATTR_T', sysdate, count(*) from KRIM_TYP_ATTR_T union
select 'KRIM_TYP_T', sysdate, count(*) from KRIM_TYP_T union
select 'KRNS_ADHOC_RTE_ACTN_RECIP_T', sysdate, count(*) from KRNS_ADHOC_RTE_ACTN_RECIP_T union
select 'KRNS_ATT_T', sysdate, count(*) from KRNS_ATT_T union
select 'KRNS_CAMPUS_T', sysdate, count(*) from KRNS_CAMPUS_T union
select 'KRNS_CMP_TYP_T', sysdate, count(*) from KRNS_CMP_TYP_T union
select 'KRNS_DOC_HDR_T', sysdate, count(*) from KRNS_DOC_HDR_T union
select 'KRNS_LOOKUP_RSLT_T', sysdate, count(*) from KRNS_LOOKUP_RSLT_T union
select 'KRNS_LOOKUP_SEL_T', sysdate, count(*) from KRNS_LOOKUP_SEL_T union
select 'KRNS_MAINT_DOC_ATT_T', sysdate, count(*) from KRNS_MAINT_DOC_ATT_T union
select 'KRNS_MAINT_DOC_T', sysdate, count(*) from KRNS_MAINT_DOC_T union
select 'KRNS_MAINT_LOCK_T', sysdate, count(*) from KRNS_MAINT_LOCK_T union
select 'KRNS_NMSPC_T', sysdate, count(*) from KRNS_NMSPC_T union
select 'KRNS_NTE_T', sysdate, count(*) from KRNS_NTE_T union
select 'KRNS_NTE_TYP_T', sysdate, count(*) from KRNS_NTE_TYP_T union
select 'KRNS_PARM_DTL_TYP_T', sysdate, count(*) from KRNS_PARM_DTL_TYP_T union
select 'KRNS_PARM_T', sysdate, count(*) from KRNS_PARM_T union
select 'KRNS_PARM_TYP_T', sysdate, count(*) from KRNS_PARM_TYP_T union
select 'KRNS_PESSIMISTIC_LOCK_T', sysdate, count(*) from KRNS_PESSIMISTIC_LOCK_T union
select 'KRNS_SESN_DOC_T', sysdate, count(*) from KRNS_SESN_DOC_T union
select 'KRSB_BAM_PARM_T', sysdate, count(*) from KRSB_BAM_PARM_T union
select 'KRSB_BAM_T', sysdate, count(*) from KRSB_BAM_T union
select 'KRSB_FLT_SVC_DEF_T', sysdate, count(*) from KRSB_FLT_SVC_DEF_T union
select 'KRSB_MSG_PYLD_T', sysdate, count(*) from KRSB_MSG_PYLD_T union
select 'KRSB_MSG_QUE_T', sysdate, count(*) from KRSB_MSG_QUE_T union
select 'KRSB_QRTZ_BLOB_TRIGGERS', sysdate, count(*) from KRSB_QRTZ_BLOB_TRIGGERS union
select 'KRSB_QRTZ_CALENDARS', sysdate, count(*) from KRSB_QRTZ_CALENDARS union
select 'KRSB_QRTZ_CRON_TRIGGERS', sysdate, count(*) from KRSB_QRTZ_CRON_TRIGGERS union
select 'KRSB_QRTZ_FIRED_TRIGGERS', sysdate, count(*) from KRSB_QRTZ_FIRED_TRIGGERS union
select 'KRSB_QRTZ_JOB_DETAILS', sysdate, count(*) from KRSB_QRTZ_JOB_DETAILS union
select 'KRSB_QRTZ_JOB_LISTENERS', sysdate, count(*) from KRSB_QRTZ_JOB_LISTENERS union
select 'KRSB_QRTZ_LOCKS', sysdate, count(*) from KRSB_QRTZ_LOCKS union
select 'KRSB_QRTZ_PAUSED_TRIGGER_GRPS', sysdate, count(*) from KRSB_QRTZ_PAUSED_TRIGGER_GRPS union
select 'KRSB_QRTZ_SCHEDULER_STATE', sysdate, count(*) from KRSB_QRTZ_SCHEDULER_STATE union
select 'KRSB_QRTZ_SIMPLE_TRIGGERS', sysdate, count(*) from KRSB_QRTZ_SIMPLE_TRIGGERS union
select 'KRSB_QRTZ_TRIGGERS', sysdate, count(*) from KRSB_QRTZ_TRIGGERS union
select 'KRSB_QRTZ_TRIGGER_LISTENERS', sysdate, count(*) from KRSB_QRTZ_TRIGGER_LISTENERS union
select 'KRSB_SVC_DEF_T', sysdate, count(*) from KRSB_SVC_DEF_T union
select 'KR_COUNTRY_T', sysdate, count(*) from KR_COUNTRY_T union
select 'KR_COUNTY_T', sysdate, count(*) from KR_COUNTY_T union
select 'KR_POSTAL_CODE_T', sysdate, count(*) from KR_POSTAL_CODE_T union
select 'KR_STATE_T', sysdate, count(*) from KR_STATE_T union
select 'LOCATION_TYPE', sysdate, count(*) from LOCATION_TYPE union
select 'MAIL_BY', sysdate, count(*) from MAIL_BY union
select 'MAIL_TYPE', sysdate, count(*) from MAIL_TYPE union
select 'MEMBERSHIP_ROLE', sysdate, count(*) from MEMBERSHIP_ROLE union
select 'MINUTE_ENTRY_TYPE', sysdate, count(*) from MINUTE_ENTRY_TYPE union
select 'MSG_OF_THE_DAY', sysdate, count(*) from MSG_OF_THE_DAY union
select 'NARRATIVE', sysdate, count(*) from NARRATIVE union
select 'NARRATIVE_ATTACHMENT', sysdate, count(*) from NARRATIVE_ATTACHMENT union
select 'NARRATIVE_STATUS', sysdate, count(*) from NARRATIVE_STATUS union
select 'NARRATIVE_TYPE', sysdate, count(*) from NARRATIVE_TYPE union
select 'NARRATIVE_USER_RIGHTS', sysdate, count(*) from NARRATIVE_USER_RIGHTS union
select 'NOTICE_OF_OPPORTUNITY', sysdate, count(*) from NOTICE_OF_OPPORTUNITY union
select 'NOTIFICATION', sysdate, count(*) from NOTIFICATION union
select 'NOTIFICATION_TYPE', sysdate, count(*) from NOTIFICATION_TYPE union
select 'NOTIFICATION_TYPE_RECIPIENT', sysdate, count(*) from NOTIFICATION_TYPE_RECIPIENT union
select 'NSF_CODES', sysdate, count(*) from NSF_CODES union
select 'ORGANIZATION', sysdate, count(*) from ORGANIZATION union
select 'ORGANIZATION_AUDIT', sysdate, count(*) from ORGANIZATION_AUDIT union
select 'ORGANIZATION_IDC', sysdate, count(*) from ORGANIZATION_IDC union
select 'ORGANIZATION_TYPE', sysdate, count(*) from ORGANIZATION_TYPE union
select 'ORGANIZATION_TYPE_LIST', sysdate, count(*) from ORGANIZATION_TYPE_LIST union
select 'ORGANIZATION_YNQ', sysdate, count(*) from ORGANIZATION_YNQ union
select 'PENDING_TRANSACTIONS', sysdate, count(*) from PENDING_TRANSACTIONS union
select 'PERSON_APPOINTMENT', sysdate, count(*) from PERSON_APPOINTMENT union
select 'PERSON_DEGREE', sysdate, count(*) from PERSON_DEGREE union
select 'PERSON_EDITABLE_FIELDS', sysdate, count(*) from PERSON_EDITABLE_FIELDS union
select 'PERSON_EXT_T', sysdate, count(*) from PERSON_EXT_T union
select 'PERSON_TRAINING', sysdate, count(*) from PERSON_TRAINING union
select 'PROPOSAL', sysdate, count(*) from PROPOSAL union
select 'PROPOSAL_ADMIN_DETAILS', sysdate, count(*) from PROPOSAL_ADMIN_DETAILS union
select 'PROPOSAL_COMMENTS', sysdate, count(*) from PROPOSAL_COMMENTS union
select 'PROPOSAL_COST_SHARING', sysdate, count(*) from PROPOSAL_COST_SHARING union
select 'PROPOSAL_CUSTOM_DATA', sysdate, count(*) from PROPOSAL_CUSTOM_DATA union
select 'PROPOSAL_EXEMPT_NUMBER', sysdate, count(*) from PROPOSAL_EXEMPT_NUMBER union
select 'PROPOSAL_IDC_RATE', sysdate, count(*) from PROPOSAL_IDC_RATE union
select 'PROPOSAL_INV_CERTIFICATION', sysdate, count(*) from PROPOSAL_INV_CERTIFICATION union
select 'PROPOSAL_IP_REVIEW_JOIN', sysdate, count(*) from PROPOSAL_IP_REVIEW_JOIN union
select 'PROPOSAL_IP_REV_ACTIVITY', sysdate, count(*) from PROPOSAL_IP_REV_ACTIVITY union
select 'PROPOSAL_LOG', sysdate, count(*) from PROPOSAL_LOG union
select 'PROPOSAL_LOG_STATUS', sysdate, count(*) from PROPOSAL_LOG_STATUS union
select 'PROPOSAL_LOG_TYPE', sysdate, count(*) from PROPOSAL_LOG_TYPE union
select 'PROPOSAL_NOTEPAD', sysdate, count(*) from PROPOSAL_NOTEPAD union
select 'PROPOSAL_PERSONS', sysdate, count(*) from PROPOSAL_PERSONS union
select 'PROPOSAL_PERSON_UNITS', sysdate, count(*) from PROPOSAL_PERSON_UNITS union
select 'PROPOSAL_PERS_UNIT_CRED_SPLITS', sysdate, count(*) from PROPOSAL_PERS_UNIT_CRED_SPLITS union
select 'PROPOSAL_PER_CREDIT_SPLIT', sysdate, count(*) from PROPOSAL_PER_CREDIT_SPLIT union
select 'PROPOSAL_RESPONSE', sysdate, count(*) from PROPOSAL_RESPONSE union
select 'PROPOSAL_SCIENCE_KEYWORD', sysdate, count(*) from PROPOSAL_SCIENCE_KEYWORD union
select 'PROPOSAL_SPECIAL_REVIEW', sysdate, count(*) from PROPOSAL_SPECIAL_REVIEW union
select 'PROPOSAL_STATE', sysdate, count(*) from PROPOSAL_STATE union
select 'PROPOSAL_STATUS', sysdate, count(*) from PROPOSAL_STATUS union
select 'PROPOSAL_TYPE', sysdate, count(*) from PROPOSAL_TYPE union
select 'PROPOSAL_UNITS', sysdate, count(*) from PROPOSAL_UNITS union
select 'PROPOSAL_UNIT_CONTACTS', sysdate, count(*) from PROPOSAL_UNIT_CONTACTS union
select 'PROPOSAL_UNIT_CREDIT_SPLIT', sysdate, count(*) from PROPOSAL_UNIT_CREDIT_SPLIT union
select 'PROP_ROLE_TEMPLATE', sysdate, count(*) from PROP_ROLE_TEMPLATE union
select 'PROTOCOL', sysdate, count(*) from PROTOCOL union
select 'PROTOCOL_ACTIONS', sysdate, count(*) from PROTOCOL_ACTIONS union
select 'PROTOCOL_ACTION_TYPE', sysdate, count(*) from PROTOCOL_ACTION_TYPE union
select 'PROTOCOL_ATTACHMENT_GROUP', sysdate, count(*) from PROTOCOL_ATTACHMENT_GROUP union
select 'PROTOCOL_ATTACHMENT_PERSONNEL', sysdate, count(*) from PROTOCOL_ATTACHMENT_PERSONNEL union
select 'PROTOCOL_ATTACHMENT_PROTOCOL', sysdate, count(*) from PROTOCOL_ATTACHMENT_PROTOCOL union
select 'PROTOCOL_ATTACHMENT_STATUS', sysdate, count(*) from PROTOCOL_ATTACHMENT_STATUS union
select 'PROTOCOL_ATTACHMENT_TYPE', sysdate, count(*) from PROTOCOL_ATTACHMENT_TYPE union
select 'PROTOCOL_ATTACHMENT_TYPE_GROUP', sysdate, count(*) from PROTOCOL_ATTACHMENT_TYPE_GROUP union
select 'PROTOCOL_CONTINGENCY', sysdate, count(*) from PROTOCOL_CONTINGENCY union
select 'PROTOCOL_CORRESPONDENCE', sysdate, count(*) from PROTOCOL_CORRESPONDENCE union
select 'PROTOCOL_DOCUMENT', sysdate, count(*) from PROTOCOL_DOCUMENT union
select 'PROTOCOL_EXEMPT_CHKLST', sysdate, count(*) from PROTOCOL_EXEMPT_CHKLST union
select 'PROTOCOL_EXEMPT_NUMBER', sysdate, count(*) from PROTOCOL_EXEMPT_NUMBER union
select 'PROTOCOL_EXPIDITED_CHKLST', sysdate, count(*) from PROTOCOL_EXPIDITED_CHKLST union
select 'PROTOCOL_FUNDING_SOURCE', sysdate, count(*) from PROTOCOL_FUNDING_SOURCE union
select 'PROTOCOL_LOCATION', sysdate, count(*) from PROTOCOL_LOCATION union
select 'PROTOCOL_MODULES', sysdate, count(*) from PROTOCOL_MODULES union
select 'PROTOCOL_NOTEPAD', sysdate, count(*) from PROTOCOL_NOTEPAD union
select 'PROTOCOL_ONLN_RVWS', sysdate, count(*) from PROTOCOL_ONLN_RVWS union
select 'PROTOCOL_ONLN_RVW_DETERM_RECOM', sysdate, count(*) from PROTOCOL_ONLN_RVW_DETERM_RECOM union
select 'PROTOCOL_ONLN_RVW_DOCUMENT', sysdate, count(*) from PROTOCOL_ONLN_RVW_DOCUMENT union
select 'PROTOCOL_ONLN_RVW_STATUS', sysdate, count(*) from PROTOCOL_ONLN_RVW_STATUS union
select 'PROTOCOL_ORG_TYPE', sysdate, count(*) from PROTOCOL_ORG_TYPE union
select 'PROTOCOL_PERSONS', sysdate, count(*) from PROTOCOL_PERSONS union
select 'PROTOCOL_PERSON_ROLES', sysdate, count(*) from PROTOCOL_PERSON_ROLES union
select 'PROTOCOL_PERSON_ROLE_MAPPING', sysdate, count(*) from PROTOCOL_PERSON_ROLE_MAPPING union
select 'PROTOCOL_REFERENCES', sysdate, count(*) from PROTOCOL_REFERENCES union
select 'PROTOCOL_REFERENCE_TYPE', sysdate, count(*) from PROTOCOL_REFERENCE_TYPE union
select 'PROTOCOL_RESEARCH_AREAS', sysdate, count(*) from PROTOCOL_RESEARCH_AREAS union
select 'PROTOCOL_REVIEWERS', sysdate, count(*) from PROTOCOL_REVIEWERS union
select 'PROTOCOL_REVIEWER_TYPE', sysdate, count(*) from PROTOCOL_REVIEWER_TYPE union
select 'PROTOCOL_REVIEW_TYPE', sysdate, count(*) from PROTOCOL_REVIEW_TYPE union
select 'PROTOCOL_RISK_LEVELS', sysdate, count(*) from PROTOCOL_RISK_LEVELS union
select 'PROTOCOL_SPECIAL_REVIEW', sysdate, count(*) from PROTOCOL_SPECIAL_REVIEW union
select 'PROTOCOL_STATUS', sysdate, count(*) from PROTOCOL_STATUS union
select 'PROTOCOL_SUBMISSION', sysdate, count(*) from PROTOCOL_SUBMISSION union
select 'PROTOCOL_SUBMISSION_DOC', sysdate, count(*) from PROTOCOL_SUBMISSION_DOC union
select 'PROTOCOL_TYPE', sysdate, count(*) from PROTOCOL_TYPE union
select 'PROTOCOL_UNITS', sysdate, count(*) from PROTOCOL_UNITS union
select 'PROTOCOL_VOTE_ABSTAINEES', sysdate, count(*) from PROTOCOL_VOTE_ABSTAINEES union
select 'PROTOCOL_VOTE_RECUSED', sysdate, count(*) from PROTOCOL_VOTE_RECUSED union
select 'PROTOCOL_VULNERABLE_SUB', sysdate, count(*) from PROTOCOL_VULNERABLE_SUB union
select 'PROTO_AMEND_RENEWAL', sysdate, count(*) from PROTO_AMEND_RENEWAL union
select 'PROTO_AMEND_RENEW_MODULES', sysdate, count(*) from PROTO_AMEND_RENEW_MODULES union
select 'PROTO_CORRESP_TEMPL', sysdate, count(*) from PROTO_CORRESP_TEMPL union
select 'PROTO_CORRESP_TYPE', sysdate, count(*) from PROTO_CORRESP_TYPE union
select 'PROTO_NOTIFICATION_TEMPL', sysdate, count(*) from PROTO_NOTIFICATION_TEMPL union
select 'QUESTION', sysdate, count(*) from QUESTION union
select 'QUESTIONNAIRE', sysdate, count(*) from QUESTIONNAIRE union
select 'QUESTIONNAIRE_ANSWER', sysdate, count(*) from QUESTIONNAIRE_ANSWER union
select 'QUESTIONNAIRE_ANSWER_HEADER', sysdate, count(*) from QUESTIONNAIRE_ANSWER_HEADER union
select 'QUESTIONNAIRE_CONDITION_TYPE', sysdate, count(*) from QUESTIONNAIRE_CONDITION_TYPE union
select 'QUESTIONNAIRE_QUESTIONS', sysdate, count(*) from QUESTIONNAIRE_QUESTIONS union
select 'QUESTIONNAIRE_USAGE', sysdate, count(*) from QUESTIONNAIRE_USAGE union
select 'QUESTION_EXPLANATION', sysdate, count(*) from QUESTION_EXPLANATION union
select 'QUESTION_TYPES', sysdate, count(*) from QUESTION_TYPES union
select 'RATE_CLASS', sysdate, count(*) from RATE_CLASS union
select 'RATE_CLASS_TYPE', sysdate, count(*) from RATE_CLASS_TYPE union
select 'RATE_TYPE', sysdate, count(*) from RATE_TYPE union
select 'REPORT', sysdate, count(*) from REPORT union
select 'REPORT_CLASS', sysdate, count(*) from REPORT_CLASS union
select 'RESEARCH_AREAS', sysdate, count(*) from RESEARCH_AREAS union
select 'RIGHTS', sysdate, count(*) from RIGHTS union
select 'RISK_LEVEL', sysdate, count(*) from RISK_LEVEL union
select 'ROLE', sysdate, count(*) from ROLE union
select 'ROLE_RIGHTS', sysdate, count(*) from ROLE_RIGHTS union
select 'ROLODEX', sysdate, count(*) from ROLODEX union
select 'S2S_APPLICATION', sysdate, count(*) from S2S_APPLICATION union
select 'S2S_APP_ATTACHMENTS', sysdate, count(*) from S2S_APP_ATTACHMENTS union
select 'S2S_APP_SUBMISSION', sysdate, count(*) from S2S_APP_SUBMISSION union
select 'S2S_FORM_TO_QUESTIONNAIRE', sysdate, count(*) from S2S_FORM_TO_QUESTIONNAIRE union
select 'S2S_OPPORTUNITY', sysdate, count(*) from S2S_OPPORTUNITY union
select 'S2S_OPP_FORMS', sysdate, count(*) from S2S_OPP_FORMS union
select 'S2S_REVISION_TYPE', sysdate, count(*) from S2S_REVISION_TYPE union
select 'S2S_SUBMISSION_TYPE', sysdate, count(*) from S2S_SUBMISSION_TYPE union
select 'SCHEDULE_ACT_ITEM_TYPE', sysdate, count(*) from SCHEDULE_ACT_ITEM_TYPE union
select 'SCHEDULE_AGENDA', sysdate, count(*) from SCHEDULE_AGENDA union
select 'SCHEDULE_STATUS', sysdate, count(*) from SCHEDULE_STATUS union
select 'SCHOOL_CODE', sysdate, count(*) from SCHOOL_CODE union
select 'SCIENCE_KEYWORD', sysdate, count(*) from SCIENCE_KEYWORD union
select 'SPECIAL_REVIEW', sysdate, count(*) from SPECIAL_REVIEW union
select 'SPECIAL_REVIEW_USAGE', sysdate, count(*) from SPECIAL_REVIEW_USAGE union
select 'SPONSOR', sysdate, count(*) from SPONSOR union
select 'SPONSOR_FORMS', sysdate, count(*) from SPONSOR_FORMS union
select 'SPONSOR_FORM_TEMPLATES', sysdate, count(*) from SPONSOR_FORM_TEMPLATES union
select 'SPONSOR_HIERARCHY', sysdate, count(*) from SPONSOR_HIERARCHY union
select 'SPONSOR_HIERARCHY_MT', sysdate, count(*) from SPONSOR_HIERARCHY_MT union
select 'SPONSOR_TERM', sysdate, count(*) from SPONSOR_TERM union
select 'SPONSOR_TERM_TYPE', sysdate, count(*) from SPONSOR_TERM_TYPE union
select 'SPONSOR_TYPE', sysdate, count(*) from SPONSOR_TYPE union
select 'SP_REV_APPROVAL_TYPE', sysdate, count(*) from SP_REV_APPROVAL_TYPE union
select 'STATE_CODE', sysdate, count(*) from STATE_CODE union
select 'SUBMISSION_STATUS', sysdate, count(*) from SUBMISSION_STATUS union
select 'SUBMISSION_TYPE', sysdate, count(*) from SUBMISSION_TYPE union
select 'SUBMISSION_TYPE_QUALIFIER', sysdate, count(*) from SUBMISSION_TYPE_QUALIFIER union
select 'TBN', sysdate, count(*) from TBN union
select 'TIME_AND_MONEY_DOCUMENT', sysdate, count(*) from TIME_AND_MONEY_DOCUMENT union
select 'TRAINING', sysdate, count(*) from TRAINING union
select 'TRAINING_STIPEND_RATES', sysdate, count(*) from TRAINING_STIPEND_RATES union
select 'TRANSACTION_DETAILS', sysdate, count(*) from TRANSACTION_DETAILS union
select 'TRV_ACCT_USE_RT_T', sysdate, count(*) from TRV_ACCT_USE_RT_T union
select 'TST_SEARCH_ATTR_INDX_TST_DOC_T', sysdate, count(*) from TST_SEARCH_ATTR_INDX_TST_DOC_T union
select 'UH_AWARD_EXT_T', sysdate, count(*) from UH_AWARD_EXT_T union
select 'UH_UNIT_COLLEGE', sysdate, count(*) from UH_UNIT_COLLEGE union
select 'UNIT', sysdate, count(*) from UNIT union
select 'UNIT_ADMINISTRATOR', sysdate, count(*) from UNIT_ADMINISTRATOR union
select 'UNIT_ADMINISTRATOR_TYPE', sysdate, count(*) from UNIT_ADMINISTRATOR_TYPE union
select 'USER_ROLES', sysdate, count(*) from USER_ROLES union
select 'USER_TABLES_TEMP', sysdate, count(*) from USER_TABLES_TEMP union
select 'VALID_AWARD_BASIS_PAYMENT', sysdate, count(*) from VALID_AWARD_BASIS_PAYMENT union
select 'VALID_BASIS_METHOD_PMT', sysdate, count(*) from VALID_BASIS_METHOD_PMT union
select 'VALID_CALC_TYPES', sysdate, count(*) from VALID_CALC_TYPES union
select 'VALID_CE_JOB_CODES', sysdate, count(*) from VALID_CE_JOB_CODES union
select 'VALID_CE_RATE_TYPES', sysdate, count(*) from VALID_CE_RATE_TYPES union
select 'VALID_CLASS_REPORT_FREQ', sysdate, count(*) from VALID_CLASS_REPORT_FREQ union
select 'VALID_FREQUENCY_BASE', sysdate, count(*) from VALID_FREQUENCY_BASE union
select 'VALID_NARR_FORMS', sysdate, count(*) from VALID_NARR_FORMS union
select 'VALID_PROTO_ACTION_ACTION', sysdate, count(*) from VALID_PROTO_ACTION_ACTION union
select 'VALID_PROTO_ACTION_CORESP', sysdate, count(*) from VALID_PROTO_ACTION_CORESP union
select 'VALID_PROTO_SUB_REV_TYPE', sysdate, count(*) from VALID_PROTO_SUB_REV_TYPE union
select 'VALID_PROTO_SUB_TYPE_QUAL', sysdate, count(*) from VALID_PROTO_SUB_TYPE_QUAL union
select 'VALID_RATES', sysdate, count(*) from VALID_RATES union
select 'VALID_SP_REV_APPROVAL', sysdate, count(*) from VALID_SP_REV_APPROVAL union
select 'VERSION_HISTORY', sysdate, count(*) from VERSION_HISTORY union
select 'VULNERABLE_SUBJECT_TYPE', sysdate, count(*) from VULNERABLE_SUBJECT_TYPE union
select 'WATERMARK', sysdate, count(*) from WATERMARK union
select 'YNQ', sysdate, count(*) from YNQ union
select 'YNQ_EXPLANATION', sysdate, count(*) from YNQ_EXPLANATION union
select 'YNQ_EXPLANATION_TYPE', sysdate, count(*) from YNQ_EXPLANATION_TYPE;
