select "KC_AWARD_FUNDING_PROPOSALS"."AWARD_ID", "KC_AWARD_FUNDING_PROPOSALS"."PROPOSAL_ID" from "DM_INFOED_ADMINISTRATOR"."KC_AWARD_FUNDING_PROPOSALS" "KC_AWARD_FUNDING_PROPOSALS" select "AWARD_FUNDING_PROPOSALS"."AWARD_ID", "AWARD_FUNDING_PROPOSALS"."PROPOSAL_ID" from "KCDEV31A"."AWARD_FUNDING_PROPOSALS" "AWARD_FUNDING_PROPOSALS" select "KC_AWARD"."AWARD_ID", "KC_AWARD"."AWARD_NUMBER", "KC_AWARD"."LEAD_UNIT_NUMBER", "KC_AWARD"."SPONSOR_AWARD_NUMBER", "KC_AWARD"."SPONSOR_CODE", "KC_AWARD"."TITLE", "KC_AWARD"."NOTICE_DATE", "KC_AWARD"."UPDATE_TIMESTAMP", "KC_AWARD"."AWARD_EFFECTIVE_DATE", "KC_AWARD"."ACTIVITY_TYPE_CODE" from "DM_INFOED_ADMINISTRATOR"."KC_AWARD" "KC_AWARD" select "AWARD"."AWARD_ID", "AWARD"."AWARD_NUMBER", "AWARD"."LEAD_UNIT_NUMBER", "AWARD"."SPONSOR_AWARD_NUMBER", "AWARD"."SPONSOR_CODE", "AWARD"."TITLE", "AWARD"."NOTICE_DATE", "AWARD"."UPDATE_TIMESTAMP", "AWARD"."AWARD_EFFECTIVE_DATE", "AWARD"."ACTIVITY_TYPE_CODE" from "KCDEV31A"."AWARD" "AWARD" select "KC_PROPOSAL"."PROPOSAL_ID", "KC_PROPOSAL"."PROPOSAL_NUMBER", "KC_PROPOSAL"."LEAD_UNIT_NUMBER", "KC_PROPOSAL"."CURRENT_AWARD_NUMBER", "KC_PROPOSAL"."SPONSOR_CODE", "KC_PROPOSAL"."TITLE", "KC_PROPOSAL"."TOTAL_DIRECT_COST_TOTAL", "KC_PROPOSAL"."PROPOSAL_TYPE_CODE", "KC_PROPOSAL"."UPDATE_TIMESTAMP", "KC_PROPOSAL"."REQUESTED_START_DATE_TOTAL", "KC_PROPOSAL"."REQUESTED_END_DATE_TOTAL", "KC_PROPOSAL"."ACTIVITY_TYPE_CODE" from "DM_INFOED_ADMINISTRATOR"."KC_PROPOSAL" "KC_PROPOSAL" select "PROPOSAL"."PROPOSAL_ID", "PROPOSAL"."PROPOSAL_NUMBER", "PROPOSAL"."LEAD_UNIT_NUMBER", "PROPOSAL"."CURRENT_AWARD_NUMBER", "PROPOSAL"."SPONSOR_CODE", "PROPOSAL"."TITLE", "PROPOSAL"."TOTAL_DIRECT_COST_TOTAL", "PROPOSAL"."PROPOSAL_TYPE_CODE", "PROPOSAL"."UPDATE_TIMESTAMP", "PROPOSAL"."REQUESTED_START_DATE_TOTAL", "PROPOSAL"."REQUESTED_END_DATE_TOTAL", "PROPOSAL"."ACTIVITY_TYPE_CODE" from "KCDEV31A"."PROPOSAL" "PROPOSAL"

select "KC_AWARD_FUNDING_PROPOSALS"."AWARD_ID", "KC_AWARD_FUNDING_PROPOSALS"."PROPOSAL_ID" from "DM_INFOED_ADMINISTRATOR"."KC_AWARD_FUNDING_PROPOSALS" "KC_AWARD_FUNDING_PROPOSALS" select "AWARD_FUNDING_PROPOSALS"."AWARD_ID", "AWARD_FUNDING_PROPOSALS"."PROPOSAL_ID" from "KCDEV31A"."AWARD_FUNDING_PROPOSALS" "AWARD_FUNDING_PROPOSALS" select "KC_AWARD"."AWARD_ID", "KC_AWARD"."AWARD_NUMBER", "KC_AWARD"."LEAD_UNIT_NUMBER", "KC_AWARD"."SPONSOR_AWARD_NUMBER", "KC_AWARD"."SPONSOR_CODE", "KC_AWARD"."TITLE", "KC_AWARD"."NOTICE_DATE", "KC_AWARD"."UPDATE_TIMESTAMP", "KC_AWARD"."AWARD_EFFECTIVE_DATE", "KC_AWARD"."ACTIVITY_TYPE_CODE" from "DM_INFOED_ADMINISTRATOR"."KC_AWARD" "KC_AWARD" select "AWARD"."AWARD_ID", "AWARD"."AWARD_NUMBER", "AWARD"."LEAD_UNIT_NUMBER", "AWARD"."SPONSOR_AWARD_NUMBER", "AWARD"."SPONSOR_CODE", "AWARD"."TITLE", "AWARD"."NOTICE_DATE", "AWARD"."UPDATE_TIMESTAMP", "AWARD"."AWARD_EFFECTIVE_DATE", "AWARD"."ACTIVITY_TYPE_CODE" from "KCDEV31A"."AWARD" "AWARD" select "KC_PROPOSAL"."PROPOSAL_ID", "KC_PROPOSAL"."PROPOSAL_NUMBER", "KC_PROPOSAL"."LEAD_UNIT_NUMBER", "KC_PROPOSAL"."CURRENT_AWARD_NUMBER", "KC_PROPOSAL"."SPONSOR_CODE", "KC_PROPOSAL"."TITLE", "KC_PROPOSAL"."TOTAL_DIRECT_COST_TOTAL", "KC_PROPOSAL"."PROPOSAL_TYPE_CODE", "KC_PROPOSAL"."UPDATE_TIMESTAMP", "KC_PROPOSAL"."REQUESTED_START_DATE_TOTAL", "KC_PROPOSAL"."REQUESTED_END_DATE_TOTAL", "KC_PROPOSAL"."ACTIVITY_TYPE_CODE" from "DM_INFOED_ADMINISTRATOR"."KC_PROPOSAL" "KC_PROPOSAL" select "PROPOSAL"."PROPOSAL_ID", "PROPOSAL"."PROPOSAL_NUMBER", "PROPOSAL"."LEAD_UNIT_NUMBER", "PROPOSAL"."CURRENT_AWARD_NUMBER", "PROPOSAL"."SPONSOR_CODE", "PROPOSAL"."TITLE", "PROPOSAL"."TOTAL_DIRECT_COST_TOTAL", "PROPOSAL"."PROPOSAL_TYPE_CODE", "PROPOSAL"."UPDATE_TIMESTAMP", "PROPOSAL"."REQUESTED_START_DATE_TOTAL", "PROPOSAL"."REQUESTED_END_DATE_TOTAL", "PROPOSAL"."ACTIVITY_TYPE_CODE" from "KCDEV31A"."PROPOSAL" "PROPOSAL"

select "KC_AWARD_FUNDING_PROPOSALS"."AWARD_ID",
       "KC_AWARD_FUNDING_PROPOSALS"."PROPOSAL_ID"
from "DM_INFOED_ADMINISTRATOR"."KC_AWARD_FUNDING_PROPOSALS"
     "KC_AWARD_FUNDING_PROPOSALS";
     
select AWARD_ID, count(proposal_id)
from award_funding_proposals
group by AWARD_ID
having count(proposal_id) > 1;

select award.AWARD_ID, proposal.proposal_id,award.award_number,proposal.proposal_number
from award_funding_proposals,
    award,
    proposal
where award_funding_proposals.award_id = award.award_id 
  and award_funding_proposals.proposal_id = proposal.proposal_id
  and award_funding_proposals.proposal_id in ('1005','1010','1013','1014','1017','1020','1021','1034',
'1062','1063','1064') order by proposal.proposal_id,award.award_id;


select *
from "KCDEV31A"."AWARD_FUNDING_PROPOSALS"
     "AWARD_FUNDING_PROPOSALS" 
where award_id = '1337';

select award_number from award where award_id = '1337';
