drop table UH_INTERNAL_AWARD_NOTEPAD;

CREATE TABLE UH_INTERNAL_AWARD_NOTEPAD 
   (	
   AWARD_NOTEPAD_ID NUMBER(12,0), 
	 AWARD_NUMBER VARCHAR2(12 CHAR) NOT NULL ENABLE, 
	 ENTRY_NUMBER NUMBER(4,0) NOT NULL ENABLE, 
	 COMMENTS CLOB NOT NULL ENABLE, 
	 RESTRICTED_VIEW CHAR(1 CHAR) NOT NULL ENABLE, 
	 UPDATE_TIMESTAMP DATE NOT NULL ENABLE, 
	 UPDATE_USER VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	 VER_NBR NUMBER(8,0) DEFAULT 1 NOT NULL ENABLE, 
	 CREATE_TIMESTAMP DATE NOT NULL ENABLE, 
	 NOTE_TOPIC VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	 AWARD_ID NUMBER(22,0) NOT NULL ENABLE, 
	 OBJ_ID VARCHAR2(36 CHAR) NOT NULL ENABLE, 
	 CREATE_USER VARCHAR2(60 CHAR) NOT NULL ENABLE 
	 );
   
CREATE UNIQUE INDEX UH_INT_AWARD_NOTEPADP1 ON UH_INTERNAL_AWARD_NOTEPAD ("AWARD_NOTEPAD_ID");

CREATE INDEX UQ_UH_INT_AWARD_NOTEPAD ON UH_INTERNAL_AWARD_NOTEPAD ("AWARD_NUMBER", "ENTRY_NUMBER");
   
CREATE SEQUENCE SEQ_UH_INT_AWARD_NOTEPAD_ID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
