ALTER TABLE UNIT_ADMINISTRATOR DROP CONSTRAINT UNIT_ADMINISTRATORP1;

ALTER TABLE UNIT_ADMINISTRATOR ADD CONSTRAINT UNIT_ADMINISTRATORP1 PRIMARY KEY ("UNIT_NUMBER", "PERSON_ID", "UNIT_ADMINISTRATOR_TYPE_CODE");


  